// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace TaskPlanner.Resources {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var assembly = typeof(SharedResource).Assembly;
                    var baseName = "TaskPlanner.Resources.SharedResource";
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        baseName, assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        // Define explicit properties for key resource strings
        public static string TestKey {
            get {
                return ResourceManager.GetString("TestKey", resourceCulture);
            }
        }
        
        public static string TaskPlannerTitle {
            get {
                return ResourceManager.GetString("TaskPlannerTitle", resourceCulture);
            }
        }
        
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        public static string WelcomeLead {
            get {
                return ResourceManager.GetString("WelcomeLead", resourceCulture);
            }
        }
        
        public static string AddTasksCard {
            get {
                return ResourceManager.GetString("AddTasksCard", resourceCulture);
            }
        }
        
        public static string AddTasksDesc {
            get {
                return ResourceManager.GetString("AddTasksDesc", resourceCulture);
            }
        }
        
        public static string MarkCompleteCard {
            get {
                return ResourceManager.GetString("MarkCompleteCard", resourceCulture);
            }
        }
        
        public static string MarkCompleteDesc {
            get {
                return ResourceManager.GetString("MarkCompleteDesc", resourceCulture);
            }
        }
        
        public static string MultilingualCard {
            get {
                return ResourceManager.GetString("MultilingualCard", resourceCulture);
            }
        }
        
        public static string MultilingualDesc {
            get {
                return ResourceManager.GetString("MultilingualDesc", resourceCulture);
            }
        }
        
        public static string GetStartedBtn {
            get {
                return ResourceManager.GetString("GetStartedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
